#:schema node_modules/wrangler/config-schema.json
name = "lyhs-app-backend"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat_v2"]
compatibility_date = "2025-01-02"

rules = [{ type = "Text", globs = ["**/*.yaml"] }]

[observability]
enabled = true

[[d1_databases]]
binding = "DATABASE"
database_name = "lycaapis-db"
database_id = "c154985f-2d35-411c-b4f2-8cc56fc7cfa3"

[[kv_namespaces]]
binding = "sessionKV"
id = "05dfa7f370304a55addd5cdfe0aece28"

[[kv_namespaces]]
binding = "mailKV"
id = "90e7fda58e1545f7b7e7259616c24212"
