#:schema node_modules/wrangler/config-schema.json
name = "lyhs-app-backend"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat_v2"]
compatibility_date = "2025-01-02"

rules = [{ type = "Text", globs = ["**/*.yaml"] }]

[observability]
enabled = true

[[d1_databases]]
binding = "DATABASE"
database_name = "lyhs-plus-database"
database_id = "21f251b6-3de6-4e42-9644-9e8dd26ee367"

[[kv_namespaces]]
binding = "sessionKV"
id = "3a0769a46dc34c2b9b9cf20310608166"

[[kv_namespaces]]
binding = "mailKV"
id = "096bd159f7a24a5f8e47c45c2b03110a"
