#:schema node_modules/wrangler/config-schema.json
name = "lyhs-app-backend"
main = "src/index.ts"
compatibility_date = "2024-12-30"
[observability]
enabled = true
[[d1_databases]]
binding = "DATABASE"
database_name = "lycaapis-db"
database_id = "c154985f-2d35-411c-b4f2-8cc56fc7cfa3"
